// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/jenkins-x/slack/pkg/apis/slack/v1alpha1"
	scheme "github.com/jenkins-x/slack/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SlackBotsGetter has a method to return a SlackBotInterface.
// A group's client should implement this interface.
type SlackBotsGetter interface {
	SlackBots(namespace string) SlackBotInterface
}

// SlackBotInterface has methods to work with SlackBot resources.
type SlackBotInterface interface {
	Create(*v1alpha1.SlackBot) (*v1alpha1.SlackBot, error)
	Update(*v1alpha1.SlackBot) (*v1alpha1.SlackBot, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SlackBot, error)
	List(opts v1.ListOptions) (*v1alpha1.SlackBotList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SlackBot, err error)
	SlackBotExpansion
}

// slackBots implements SlackBotInterface
type slackBots struct {
	client rest.Interface
	ns     string
}

// newSlackBots returns a SlackBots
func newSlackBots(c *SlackV1alpha1Client, namespace string) *slackBots {
	return &slackBots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the slackBot, and returns the corresponding slackBot object, and an error if there is any.
func (c *slackBots) Get(name string, options v1.GetOptions) (result *v1alpha1.SlackBot, err error) {
	result = &v1alpha1.SlackBot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slackbots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SlackBots that match those selectors.
func (c *slackBots) List(opts v1.ListOptions) (result *v1alpha1.SlackBotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SlackBotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slackbots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested slackBots.
func (c *slackBots) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("slackbots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a slackBot and creates it.  Returns the server's representation of the slackBot, and an error, if there is any.
func (c *slackBots) Create(slackBot *v1alpha1.SlackBot) (result *v1alpha1.SlackBot, err error) {
	result = &v1alpha1.SlackBot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("slackbots").
		Body(slackBot).
		Do().
		Into(result)
	return
}

// Update takes the representation of a slackBot and updates it. Returns the server's representation of the slackBot, and an error, if there is any.
func (c *slackBots) Update(slackBot *v1alpha1.SlackBot) (result *v1alpha1.SlackBot, err error) {
	result = &v1alpha1.SlackBot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slackbots").
		Name(slackBot.Name).
		Body(slackBot).
		Do().
		Into(result)
	return
}

// Delete takes name of the slackBot and deletes it. Returns an error if one occurs.
func (c *slackBots) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slackbots").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *slackBots) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slackbots").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched slackBot.
func (c *slackBots) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SlackBot, err error) {
	result = &v1alpha1.SlackBot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("slackbots").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
