// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SlackBotListerExpansion allows custom methods to be added to
// SlackBotLister.
type SlackBotListerExpansion interface{}

// SlackBotNamespaceListerExpansion allows custom methods to be added to
// SlackBotNamespaceLister.
type SlackBotNamespaceListerExpansion interface{}
