// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	slackv1alpha1 "github.com/jenkins-x-labs/slack/pkg/apis/slack/v1alpha1"
	versioned "github.com/jenkins-x-labs/slack/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x-labs/slack/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jenkins-x-labs/slack/pkg/client/listers/slack/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SlackBotInformer provides access to a shared informer and lister for
// SlackBots.
type SlackBotInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SlackBotLister
}

type slackBotInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSlackBotInformer constructs a new informer for SlackBot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSlackBotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSlackBotInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSlackBotInformer constructs a new informer for SlackBot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSlackBotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SlackV1alpha1().SlackBots(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SlackV1alpha1().SlackBots(namespace).Watch(options)
			},
		},
		&slackv1alpha1.SlackBot{},
		resyncPeriod,
		indexers,
	)
}

func (f *slackBotInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSlackBotInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *slackBotInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&slackv1alpha1.SlackBot{}, f.defaultInformer)
}

func (f *slackBotInformer) Lister() v1alpha1.SlackBotLister {
	return v1alpha1.NewSlackBotLister(f.Informer().GetIndexer())
}
